apiVersion: v1
kind: Service
metadata:
  name: token-service
spec:
  selector:
    app: token
  type: LoadBalancer
  ports:
    - name: token-port
      port: 5090
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-deployment
spec:
  selector:
    matchLabels:
      app: token
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: token
        version: v1
    spec:
      containers:
      - name: token-container
        image: token-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      imagePullSecrets: 
      - name: registry-credentials