apiVersion: v1
kind: Service
metadata:
  name: token-service
spec:
  selector:
    app: token
  type: LoadBalancer
  ports:
    - name: token-port
      port: 5090
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-deployment
spec:
  selector:
    matchLabels:
      app: token
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: token
        version: v1
    spec:
      containers:
      - name: token-container
        image: token-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: 100m
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
  name: token-service
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: token-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource 
    resource: 
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 50