# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_DB
              value: user
            - name: POSTGRES_USER
              value: bikeshare
            - name: POSTGRES_PASSWORD
              value: bikeshare
            - name: PGDATA
              value: /data/pgdata
      volumes:
      - name: postgresql-db-disk
        persistentVolumeClaim:
          claimName: postgresql-data
