###

@authToken = {{auth.response.body.$.token}}

# @name auth
POST http://{{host}}/api/Auth HTTP/1.1
Content-Type: application/json

{
    "username": "daniel",
    "password": "daniel"
}

###

POST http://{{host}}/api/Users HTTP/1.1
Content-Type: application/json

{
    "username": "daniel",
    "password": "daniel"
}

###

PUT http://{{host}}/api/tokens HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhbmllbDEiLCJ1c2VyVHlwZSI6IlVTRVIiLCJyb2xlIjoiVVNFUiIsIm5iZiI6MTY0NzQ3MDU5MCwiZXhwIjoxNjQ4MDc1MzkwLCJpYXQiOjE2NDc0NzA1OTB9.hPjG0n7tkPd1RcrJ8cFij-_aPoqtcPtt478QfE_qD7s

{
    "key": "daniel2",
    "token": "daniel"
}

###

@authToken = {{auth.response.body.$.token}}

# @name auth
POST http://localhost:5010/api/Auth HTTP/1.1
Content-Type: application/json
UserId: daniel

{
    "username": "daniel",
    "password": "daniel"
}

###

POST  http://localhost:5060/TravelEvent
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "Longitude": 27,
    "Latitude": 12.1
}

###

POST http://{{host}}/api/Bikes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "brand": "renault",
  "model": "clio",
  "stats": {
    "chargeLevel": 100,
    "serviceMinutes": 10
  },
  "coordinates": {
    "latitude": 41.2371735,     
    "longitude": -8.1393132
  }
}


###

GET http://{{host}}/api/docks/nearby?coordinates.latitude=41.2371735&coordinates.longitude=-8.142685&radius=100&onlyAvailable=false HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET  http://localhost:5050/api/Bikes
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Create Rental 

POST http://localhost:5050/api/rentals
Content-Type: application/json
Authorization: Bearer {{authToken}}
UserId: danielpinto1

{
  "bikeId": "809b4d1e-23e2-41fb-bc23-069254e32b0f",
  "username": "danielpinto1"
}

###

GET  http://{{host}}/api/users/daniel
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

GET http://{{host}}/api/rentals
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

POST http://{{host}}/api/rentals HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
UserId: daniel

{
  "originDockId":"53ce1a33-2b6a-4a3a-a4d3-95555ab60edf",
  "bikeId": "da9625ca-a099-41d6-92bc-cdc9a473d49b"
  //"bikeId": "f4b18777-2d82-492e-b7e3-de9eb1ed8812"
}

###

GET http://192.168.1.199:8099/api/Payments/rental/51269dfe-a81c-4567-956f-3a500878fc82
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET http://192.168.1.199:6030/api/Payments/rental/51269dfe-a81c-4567-956f-3a500878fc82
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST http://{{host}}/api/users/me/credit-cards HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
Cache-Control: no-cache

{
    "cardNumber": "123",
    "cardHolderName": "daniel",
    "cvvCode": "123",
    "expiryDate": "12/22"
}

###

GET http://{{host}}/api/users/me/credit-cards HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 
DELETE http://{{host}}/api/users/me/credit-cards/123 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET http://{{host}}/api/rentals/history HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET http://{{host}}/api/travel/rental/f2fcc7e6-5b9d-45c9-8231-056efbf52777
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST http://{{host}}/api/travel HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "coordinates": {
        "latitude": 41.23837936576801,
        "longitude": -8.139483094607279
    },
    "rentalId": "51269dfe-a81c-4567-956f-3a500878fc82",
    "username": "daniel"
}

###

GET http://{{host}}/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}



### 

POST http://{{host}}/api/feedbacks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "rentalId": "51269dfe-a81c-4567-956f-3a500878fc82",
    "message": "very good",
    "rating": 5
}

###

GET http://{{host}}/api/feedbacks?rentalId=471dc2b0-1172-46ef-b264-ffbfd8af49ec HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
