apiVersion: v1
kind: Service
metadata:
  name: travel-event-service
spec:
  selector:
    app:  travel-event-service
  type: LoadBalancer
  ports:
    - name:  travel-event-service-port
      port: 6050
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  travel-event-service-deployment
spec:
  selector:
    matchLabels:
      app:  travel-event-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  travel-event-service
        version: v1
    spec:
      containers:
      - name:  travel-event-service-container
        image:  travel-event-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: 100m
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
  name: travel-event-service
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travel-event-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource 
    resource: 
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 50
    