apiVersion: v1
kind: Service
metadata:
  name: bike-service
spec:
  selector:
    app:  bike-service
  type: LoadBalancer
  ports:
    - name:  bike-service-port
      port: 5020
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bike-service-deployment
spec:
  selector:
    matchLabels:
      app:  bike-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  bike-service
        version: v1
    spec:
      containers:
      - name:  bike-service-container
        image:  bike-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80