apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app:  api-gateway
  type: LoadBalancer
  ports:
    - name:  api-gateway-port
      port: 8099
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-gateway-deployment
spec:
  selector:
    matchLabels:
      app:  api-gateway
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  api-gateway
        version: v1
    spec:
      containers:
      - name:  api-gateway-container
        image:  api-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
            
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
  name: api-gateway-service
spec: 
  maxReplicas: 2 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80

    