apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app:  notification-service
  type: LoadBalancer
  ports:
    - name:  notification-service-port
      port: 5080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  notification-service-deployment
spec:
  selector:
    matchLabels:
      app:  notification-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  notification-service
        version: v1
    spec:
      containers:
      - name:  notification-container
        image:  notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
            
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
  name: notification-service
spec: 
  maxReplicas: 2 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80
