apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: LoadBalancer
  ports:
    - name: payment-port
      port: 6030
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      containers:
      - name: payment-container
        image: payment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80