apiVersion: v1
kind: Service
metadata:
  name: payment-calculator-service
spec:
  selector:
    app: payment-calculator
  type: LoadBalancer
  ports:
    - name: payment-calculator-port
      port: 6040
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-calculator-deployment
spec:
  selector:
    matchLabels:
      app: payment-calculator
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-calculator
        version: v1
    spec:
      containers:
      - name: payment-calculator-container
        image: payment-calculator-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80