apiVersion: v1
kind: Service
metadata:
  name: payment-calculator-service
spec:
  selector:
    app: payment-calculator-service
  type: LoadBalancer
  ports:
    - name: payment-calculator-service-port
      port: 6040
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-calculator-service-deployment
spec:
  selector:
    matchLabels:
      app: payment-calculator-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-calculator-service
        version: v1
    spec:
      containers:
      - name: payment-calculator-service-container
        image: payment-calculator-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
            
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
  name: payment-calculator-service
spec: 
  maxReplicas: 2 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-calculator-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80
