apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  selector:
    app:  feedback-service
  type: LoadBalancer
  ports:
    - name:  feedback-service-port
      port: 5030
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  feedback-service-deployment
spec:
  selector:
    matchLabels:
      app:  feedback-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  feedback-service
        version: v1
    spec:
      containers:
      - name:  feedback-service-container
        image:  feedback-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      imagePullSecrets: 
      - name: registry-credentials