apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app:  user-service
  type: LoadBalancer
  ports:
    - name:  user-service-port
      port: 5040
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user-service-deployment
spec:
  selector:
    matchLabels:
      app:  user-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  user-service
        version: v1
    spec:
      containers:
      - name:  user-service-container
        image:  user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80