apiVersion: v1
kind: Service
metadata:
  name: dock-service
spec:
  selector:
    app: dock-service
  type: LoadBalancer
  ports:
    - name: dock-service-port
      port: 6010
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dock-service-deployment
spec:
  selector:
    matchLabels:
      app: dock-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: dock-service
        version: v1
    spec:
      containers:
        - name: dock-service-container
          image: dock-service:latest
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production  
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2
metadata: 
  name: dock-service
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dock-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80
