apiVersion: v1
kind: Service
metadata:
  name: dock-service
spec:
  selector:
    app: dock-service
  type: LoadBalancer
  ports:
    - name: dock-service-port
      port: 6010
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dock-service-deployment
spec:
  selector:
    matchLabels:
      app: dock-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: dock-service
        version: v1
    spec:
      containers:
        - name: dock-service-container
          image: dock-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
