// <auto-generated />
using System;
using BikeService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikeService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220321002521_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeService.Models.Entities.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StatsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatsId");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeService.Models.Entities.BikeStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChargeLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BikeStats");
                });

            modelBuilder.Entity("BikeService.Models.Entities.Bike", b =>
                {
                    b.HasOne("BikeService.Models.Entities.BikeStats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
