apiVersion: v1
kind: Service
metadata:
  name: travel-service
spec:
  selector:
    app:  travel-service
  type: LoadBalancer
  ports:
    - name:  travel-service-port
      port: 5060
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  travel-service-deployment
spec:
  selector:
    matchLabels:
      app:  travel-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  travel-service
        version: v1
    spec:
      containers:
      - name:  travel-service-container
        image:  travel-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80