apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app:  auth-service
  type: LoadBalancer
  ports:
    - name:  auth-service-port
      port: 5010
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth-service-deployment
spec:
  selector:
    matchLabels:
      app:  auth-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app:  auth-service
        version: v1
    spec:
      containers:
      - name:  auth-service-container
        image:  auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80